### ISSUE TITLE
DNS泄漏

### ISSUE THREAD

**Issue by Ella-Alinda** [taamarin/box_for_magisk#101]
下面为部分配置文件

Setting.ini
```
# set the port numbers for tproxy and redir
tproxy_port="9898"
redir_port="9797"

# enable/disable port detection: true / false
port_detect="true"

# enable/disable IPv6: true / false
ipv6="true"

# list of available kernel binaries
bin_list=( "clash" "sing-box" "xray" "v2fly" )

# for run and download premium or mihomo
# put kernel premium and mihomo into /data/adb/box/bin directory
xclash_option="mihomo"
# select the client to use : clash / sing-box / xray / v2fly
bin_name="clash"

# This script is used to set the user and group for the BFM core files.
box_user_group="root:net_admin"

# redirect: tcp only,
# tproxy: for tcp + udp with tproxy,
# mixed: mode with redirect[tcp] + tun[udp]
network_mode="tproxy"
```

Clash Config.json
```
tproxy-port: 9898

mode: rule
allow-lan: true
# unified-delay: true
bind-address: '*'

log-level: silent
ipv6: true

external-controller: 0.0.0.0:9090 
# secret: "123456"
external-ui: /data/adb/box/clash/dashboard
# tcp-concurrent: false

profile:
  store-selected: true

sniffer:                           #【Meta专属】sniffer域名嗅探器
  enable: true                    # 嗅探器开关

                                   # # 开启后对 redir-host 类型识别的流量进行强制嗅探
                                   # # 包含 Tun、Redir 和 TProxy 或 DNS 为 redir-host
  force-dns-mapping: true
  parse-pure-ip: true         # 对所有未获取到域名的流量进行强制嗅探

  override-destination: true      # 是否使用嗅探结果作为实际访问,默认 true
                                   # # 全局配置,优先级低于 sniffer.sniff 实际配置
  sniff: # TLS 默认如果不配置 ports 默认嗅探 443
    TLS:
      ports: [443, 8443]
    HTTP: # 需要嗅探的端口, 默认嗅探 80
      ports: [80, 8080-8880]
      override-destination: true # 可覆盖 sniffer.override-destination
  # force-domain:
    # - +.v2ex.com
  # # 白名单,跳过嗅探结果
  # skip-domain:
    # - Mijia Cloud

tun:
  enable: true
  device: utun
  mtu: 9000
  stack: system # gvisor / lwip / system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
  # include_android_user:
    # - 0
    # - 10
  # include_package:
  # - com.android.chrome
  # exclude_package:
    # - com.whatsapp

dns:
  enable: true
  # 可选值 true/false
  # 是否解析 IPV6, 如为 false, 则回应 AAAA 的空解析
  ipv6: true

  default-nameserver:
    # - 114.114.114.114
    - 8.8.8.8
    # cloudflare
    - 1.1.1.1
    # - tls://223.5.5.5:853
    # - https://223.5.5.5/dns-query

  # dns 服务监听
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16

  fake-ip-filter:
    - '*.lan'
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
```

**Comment by Ella-Alinda** [comment]
DNS块被替换为
```
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver-policy:
    'www.baidu.com': '114.114.114.114'
    '+.internal.crop.com': '10.0.0.1'
    'geosite:cn': https://doh.pub/dns-query
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
 ```

但仍然泄漏给运营商DNS，另外tproxy似乎存在WebRTC泄漏

测试地址 https://browserleaks.com/dns
