### ISSUE TITLE
小米天气无法随新定位更新数据，FakeIP 规则填加weatherapi.market.xiaomi.com也不行。可能是我填加方法不对吧

### ISSUE THREAD

**Issue by lzlq** [taamarin/box_for_magisk#136]
如题

**Comment by lzlq** [comment]
您好，我已收到您的邮件。
..........................这是来自QQ邮箱的自动回复邮件。

**Comment by lzlq** [comment]
看规则里面有
'*.xiami.com'这个规则
我又填加了个weatherapi.market.xiaomi.com
怎么看它是否工作呢？










劉旭
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月6日(周二) 凌晨1:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taamarin/box_for_magisk] 小米天气无法随新定位更新数据，FakeIP 规则填加weatherapi.market.xiaomi.com也不行。可能是我填加方法不对吧 (Issue #136)




  
如题
  
fake-ip-filter:
 - '*.lan'
 - weatherapi.market.xiaomi.com
 
不工作吗？

**Comment by lzlq** [comment]
可以更新了，原来是我填加的地方不对😂












劉旭
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月6日(周二) 凌晨1:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taamarin/box_for_magisk] 小米天气无法随新定位更新数据，FakeIP 规则填加weatherapi.market.xiaomi.com也不行。可能是我填加方法不对吧 (Issue #136)




  
如题
  
fake-ip-filter:
 - '*.lan'
 - weatherapi.market.xiaomi.com
 
不工作吗？

**Comment by AkameKaga** [comment]
> 可以更新了，原来是我填加的地方不对😂刘旭***@***.***
> […](#)

你好，我想请问下这个应该加在哪里，我也是遇到同样的问题

**Comment by lzlq** [comment]
在一个设置文件里面，好久不用这个转神秘了












劉旭
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年6月19日(周四) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taamarin/box_for_magisk] 小米天气无法随新定位更新数据，FakeIP 规则填加weatherapi.market.xiaomi.com也不行。可能是我填加方法不对吧 (Issue #136)


AkameKaga left a comment (taamarin/box_for_magisk#136)
  
***@***.***
 …
  
你好，我想请问下这个应该加在哪里，我也是遇到同样的问题

**Comment by AkameKaga** [comment]
我知道在配置文件里，但是我是应该在规则后加上还是在哪一段加上去

**Comment by lzlq** [comment]
fake-ip-filter:
- '*.lan'
- weatherapi.market.xiaomi.com












劉旭
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年6月19日(周四) 下午4:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taamarin/box_for_magisk] 小米天气无法随新定位更新数据，FakeIP 规则填加weatherapi.market.xiaomi.com也不行。可能是我填加方法不对吧 (Issue #136)


AkameKaga left a comment (taamarin/box_for_magisk#136)
 
我知道在配置文件里，但是我是应该在规则后加上还是在哪一段加上去

**Comment by lzlq** [comment]
这个模块有很多问题，还有企业微信小程序有些也是404，这些都是必须经常用的东西，还是要自己去填加排除，所以我最后放弃改用神秘了












劉旭
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年6月19日(周四) 下午5:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [taamarin/box_for_magisk] 小米天气无法随新定位更新数据，FakeIP 规则填加weatherapi.market.xiaomi.com也不行。可能是我填加方法不对吧 (Issue #136)


AkameKaga left a comment (taamarin/box_for_magisk#136)
 
非常谢谢，我加上了，但是还是不生效，我放弃了

**Comment by 52nav** [comment]
重点就是最下面那条记录，加上就好了。

```
dns:
  enable: true
  ipv6: false
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver: [180.184.1.1, 119.29.29.29, 223.5.5.5]
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://120.53.53.53/dns-query
    - https://doh.pub/dns-query
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
```
