### ISSUE TITLE
tproxy+fake-ip下，Wi-Fi calling（vowifi）问题

### ISSUE THREAD

**Issue by TeaWu** [taamarin/box_for_magisk#142]
BFM v1.7.1
使用mihomo v1.18.8，tproxy+fake-ip模式
配置文件的ipv6均保持为false，打开日志debug
在开启clash，打开BFM的ipv6，vowifi可以正常工作，日志中会出现一些关键记录
```
time="2024-09-14T19:45:30.259150387+08:00" level=debug msg="[Process] find process 182.128.124.1 error: lstat /proc/22856: no such file or directory"
time="2024-09-14T19:45:30.261200804+08:00" level=info msg="[UDP] 192.168.31.246:44396 --> 182.128.124.1:4500 match RuleSet(ChinaIP) using DIRECT"
……
time="2024-09-14T19:46:34.155465206+08:00" level=info msg="[UDP] 192.168.31.246:41564(android.uid.phone, uid=1001) --> 182.128.124.1:4500 match RuleSet(ChinaIP) using DIRECT"
```
在开启clash，关闭BFM的ipv6，vowifi无法正常工作，日志中未发现相关的记录

求大佬指导下，怎么在ipv4下，使得vowifi正常工作

我的DNS的配置如下
```yaml
dns:
  cache-algorithm: arc # ARC（Adaptive Replacement Cache）缓存算法
  enable: true
  listen: 0.0.0.0:1053
  use-hosts: true
  prefer-h3: true
  ipv6: false
  ipv6-timeout: 300  # 单位：ms，内部双栈并发时，向上游查询 AAAA 时，等待 AAAA 的时间，默认 100ms
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  default-nameserver:
    - 223.5.5.5
    - 61.139.2.69

  nameserver:
    - quic://223.5.5.5:853
    - https://dns.alidns.com/dns-query

  proxy-server-nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query

  nameserver-policy:
    '+.pub.3gppnetwork.org': [61.139.2.69,218.6.200.139]
    'geosite:cn': https://dns.alidns.com/dns-query

  fake-ip-filter:
    - '+.lan'
    - '+.local'
    - '+.leigod.com'
    - '+.vivox.com'
    - '+.stun.+'
    - '.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'lens.l.google.com'
    - '*.mcdn.bilivideo.cn'
    - 'localhost.ptlogin2.qq.com'
    - '+.pub.3gppnetwork.org'
    - "*.moutai519.com.*"
    - "+.safe.cdn.bcebos.com"

  fallback: # 国外 DNS 服务器
    - tls://8.8.4.4#🌏 全球加速
    - tls://1.1.1.1#🌏 全球加速
    - https://dns.google/dns-query#🌏 全球加速
    - https://cloudflare-dns.com/dns-query#🌏 全球加速

  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.ai.com'
      - '+.algolia.net'
      - '+.anthropic.com'
      - '+.argotunnel.com'
      - '+.arkoselabs.com'
      - '+.auth0.com'
      - '+.azure.com'
      - '+.azureedge.net'
      - '+.bing.com'
      - '+.bingapis.com'
      - '+.bugsnag.com'
      - '+.chatgpt.com'
      - '+.claude.ai'
      - '+.cloudflare.net'
      - '+.cloudflareinsights.com'
      - '+.cohere.ai'
      - '+.docker.com'
      - '+.docker.io'
      - '+.facebook.com'
      - '+.github.com'
      - '+.githubusercontent.com'
      - '+.google'
      - '+.google.com'
      - '+.google.dev'
      - '+.googleapis.cn'
      - '+.googlevideo.com'
      - '+.identrust.com'
      - '+.instagram.com'
      - '+.intercom.io'
      - '+.live.com'
      - '+.livekit.cloud'
      - '+.meta.ai'
      - '+.microsoft.com'
      - '+.microsoftapp.net'
      - '+.minecraft.net'
      - '+.msn.com'
      - '+.openai.com'
      - '+.poe.com'
      - '+.segment.com'
      - '+.segment.io'
      - '+.sentry.io'
      - '+.synn.cc'
      - '+.stripe.com'
      - '+.t.me'
      - '+.tailscale.com'
      - '+.tailscale.io'
      - '+.twitter.com'
      - '+.usefathom.com'
      - '+.v2ex.com'
      - '+.windows.net'
      - '+.wootric.com'
      - '+.x.com'
      - '+.youtube.com'
```
