### ISSUE TITLE
怎么在使用fake-ip的同时支持包名黑/白名单？

### ISSUE THREAD

**Issue by yqs112358** [taamarin/box_for_magisk#143]
如题，目前使用mihomo最新Release版本

首先尝试裸tproxy不开黑白名单，enhance_mode使用fake-ip，box完全可以正常工作。不过系统中所有应用都会走代理
随后尝试开包名白名单，开了之后应用就连不上mihomo了。查了一下issue似乎说是tproxy黑白名单和fake-ip不兼容？

然后尝试方案2，把settings.ini里面的packages_list清空，network_mode改成tun，clash配置文件中打开tun，在配置文件中用include-package设置包名白名单，然后启动box，发现应用仍然连不上mihomo。

很好奇：
1. 为啥tproxy黑白名单与fake-ip不兼容捏
2. 有没有什么办法可以在使用fake-ip的同时支持包名黑白名单？
方案2的tun+include-package有啥问题吗，为什么也不能工作呢🤔

配置文件编写应该没有问题

**Comment by yqs112358** [comment]
方案2 mihomo配置文件部分：
```
find-process-mode: always
...
tun:
  enable: true
  stack: system
  dns-hijack:
    - "0.0.0.0:53"
    - "tcp://0.0.0.0:53"
  auto-detect-interface: true   # 自动识别出口网卡
  strict-route: true            # 严格路由模式
  gso: true                     # 启用通用分段卸载（仅Linux）
  auto-route: true              # 自动配置路由表
  # 安卓代理包名白名单
  include-package:
    - "com.microsoft.office.outlook"
    - "com.android.vending"
    - "com.openai.chatgpt"
    - "com.github.android"
    - "com.google.ar.core"
    - ......

dns:
  enable: true
  use-hosts: true
  use-system-hosts: true
  listen: 0.0.0.0:1053        # DNS监听地址
  ipv6: false

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:       # fake ip 白名单列表
    - "*.lan"
    - "*.local"
    # Xiaomi
    - "+.market.xiaomi.com"
    # Windows Connnect Detection	
    - "*.msftconnecttest.com"	
    - "*.msftncsi.com"
  fake-ip-filter-mode: blacklist
  
  default-nameserver:
    - "223.5.5.5"
  proxy-server-nameserver:
    - "https://223.5.5.5/dns-query"   # 阿里 DoH DNS
    - "https://1.12.12.12/dns-query"  # 腾讯 DoH DNS
  nameserver:
    - "system"          # 本地DNS
    - "dhcp://system"
    - "223.5.5.5"       # 阿里DNS
    - "180.76.76.76"    # 百度DNS
    - "119.29.29.29"    # 腾讯DNS
  fallback:
    - "tls://1.1.1.1#Proxy"   # CF DoT DNS
    - "tls://8.8.8.8#Proxy"   # Google DoT DNS
  fallback-filter:
    geoip: true       # 默认
    geoip-code: CN
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4
```

**Comment by yqs112358** [comment]
> ```yaml
> tun:
>   enable: true
>   mtu: 9000
>   device: tun9
>   stack: mixed
>   dns-hijack:
>     - any:53
>   auto-route: true
>   strict-route: false
>   auto-redirect: true
>   auto-detect-interface: true
>   include-android-user: [0, 10]
>   include-package:
>     - "com.microsoft.office.outlook"
>     - "com.android.vending"
>     - "com.openai.chatgpt"
>     - "com.github.android"
>     - "com.google.ar.core"
> ```

感谢，我试试捏
用的是github最新的release android arm64

**Comment by yqs112358** [comment]
排查出来应该是没在tun指定device的原因🤣在mihomo配置和settings.ini里面都指定好tun device再启动就正常了

**Comment by lacanzizek** [comment]
@yqs112358 具体是怎么弄的，求解。

**Comment by lacanzizek** [comment]
@yqs112358 具体怎么弄的，求解。

**Comment by yqs112358** [comment]
> @yqs112358 具体怎么弄的，求解。

模块的`settings.ini`里面，`network_mode`设置为`tun`
然后mihomo配置里面，把`tun`的`enable`设置为`true`，指定`device`为`utun`，然后在`include-package`里面指定安卓包名白名单

样例：
```yaml
......
tun:
  enable: true
  stack: system
  device: utun
  auto-detect-interface: true
  auto-route: true  
  ......
  include-package:
    - "com.instagram.android"
    - "com.google.android.webview"
    - "com.termux"
    - "com.microsoft.office.outlook"
    - ...
......
```
