### ISSUE TITLE
fake-ip 好像没有生效

### ISSUE THREAD

**Issue by xaotag** [taamarin/box_for_magisk#145]
```
allow-lan: true
mixed-port: 7890
mode: Rule
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 24
external-ui: ./ui
tproxy-port: 9898
redir-port: 9797
external-controller: 0.0.0.0:9090
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
profile: # 存储 select 选择记录
  store-selected: true
  
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "geosite:cn"
  nameserver:
    - https://doh.pub/dns-query
  fallback:
    - tls://8.8.8.8
    - tls://1.1.1.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  
proxy: &proxy
  interval: 3600
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 3600
proxy-providers:
  ikun:
    type: http
    path: ./proxies/ikun.yaml
    url: ""
    <<: *proxy
proxy-groups:
  - name: 🐟 漏网之鱼
    url: http://www.gstatic.com/generate_204
    type: select
    interval: 3600
    proxies:
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
      - DIRECT
  - name: 🌐 谷歌服务
    url: http://www.gstatic.com/generate_204
    type: select
    interval: 3600
    proxies:
      - 🇭🇰 香港节点
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
      - DIRECT
  - name: 微软服务
    url: http://www.gstatic.com/generate_204
    type: select
    interval: 3600
    proxies:
      - DIRECT
      - 🇭🇰 香港节点
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
      
  - name: 📲 电报消息
    url: http://www.gstatic.com/generate_204
    type: select
    interval: 3600
    proxies:
      - 🇭🇰 香港节点
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
  - name: 🎮 游戏平台
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 60
    proxies:
      - 🇭🇰 香港节点
      - DIRECT
  - name: 📗 代码平台
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 3600
    proxies:
      - 🇭🇰 香港节点
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
      - DIRECT
  - name: PIXIV
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 60
    proxies:
      - 🇭🇰 香港节点
      - 🇯🇵 日本节点
  - name: 🤖 人工智能
    type: select
    filter: "日本|美国|英国"
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - ikun
  - name: 🚫 广告过滤
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 3600
    proxies:
      - REJECT
      - DIRECT
  - name: 🇭🇰 香港节点
    type: load-balance
    filter: "香港"
    url: http://www.gstatic.com/generate_204
    interval: 600
    use: # 引入proxy-provider 使用 use 关键字
      - ikun
  - name: 🇺🇸 美国节点
    type: load-balance
    filter: "美国"
    url: http://www.gstatic.com/generate_204
    interval: 600
    use: # 引入proxy-provider 使用 use 关键字
      - ikun
  - name: 🇯🇵 日本节点
    type: load-balance
    filter: "日本"
    url: http://www.gstatic.com/generate_204
    interval: 600
    use: # 引入proxy-provider 使用 use 关键字
      - ikun
rule-providers:
  gamedown:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/GameDownload.yaml"
    path: ./profiles/rules/gamedown.yaml
    interval: 86400
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./profiles/rules/reject.yaml
    interval: 86400

rules:
  - DOMAIN,metacubexd.pages.dev,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - PROCESS-NAME,AdGuardHome,DIRECT
  - PROCESS-NAME,com.foxconn.ipebg.meet,DIRECT
  - RULE-SET,gamedown,DIRECT
  - GEOSITE,openai,🤖 人工智能
  - GEOSITE,category-ads,REJECT
  - GEOSITE,microsoft,微软服务
  - GEOSITE,google,🌐 谷歌服务
  - GEOSITE,googlefcm,🌐 谷歌服务
  - GEOSITE,youtube,🌐 谷歌服务
  - GEOSITE,steam,🎮 游戏平台
  - GEOSITE,telegram,📲 电报消息
  - GEOIP,telegram,📲 电报消息
  - GEOSITE,github,📗 代码平台
  - GEOSITE,pixiv,PIXIV
  - GEOSITE,gitlab,📗 代码平台
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - GEOSITE,cn,DIRECT
  - RULE-SET,reject,🚫 广告过滤
  - MATCH,🐟 漏网之鱼
```
![Screenshot_2024-09-26-23-51-14-463_com microsoft emmx](https://github.com/user-attachments/assets/9ddf9939-4082-436f-9427-626dd69777a2)
