### ISSUE TITLE
关于多个订阅select的问题

### ISSUE THREAD

**Issue by Beacon0219** [taamarin/box_for_magisk#29]
我在config中的proxy providers里添加了一共三个订阅链接，在proxy groups中我需要一个name为proxy，属性为select的代理组，在需要时我可以选择使用哪个订阅链接来进行代理操作，但是在proxy的use中添加proxy group名会报错无法启动，如下:
  - { name: 'proxy', type: select, use: [nano,less,Sakura] }
  - { name: 'nano', type: url-test, use: ["@nano"] }
  - { name: 'less', type: select, use: ["@less"] }
  - { name: 'Sakura', type: select, use: ["@Sakura"] }
log中错误是未找到nano,less,Sakura组，查阅clash的文档后使用的proxies字段添加group名也无法启动，请问要怎么实现proxy自选订阅代理呢？

**Comment by taamarin** [comment]
> 



> 我在config中的proxy providers里添加了一共三个订阅链接，在proxy groups中我需要一个name为proxy，属性为select的代理组，在需要时我可以选择使用哪个订阅链接来进行代理操作，但是在proxy的use中添加proxy group名会报错无法启动，如下:
> 
> * { name: 'proxy', type: select, use: [nano,less,Sakura] }
> * { name: 'nano', type: url-test, use: ["@nano"] }
> * { name: 'less', type: select, use: ["@less"] }
> * { name: 'Sakura', type: select, use: ["@Sakura"] }
>   log中错误是未找到nano,less,Sakura组，查阅clash的文档后使用的proxies字段添加group名也无法启动，请问要怎么实现proxy自选订阅代理呢？

```yaml
proxies:
proxy-groups:
  - { name: 'proxy', type: select, proxies: [nano,less,Sakura] }
  - { name: 'nano', type: url-test, use: ["@nano"] }
  - { name: 'less', type: select, use: ["@less"] }
  - { name: 'Sakura', type: select, use: ["@Sakura"] }
proxy-providers:
  "@nano":
    type: http
    url: 'your url'
    path: ./provide/node1.yml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
  "@less":
    type: http
    url: 'your url'
    path: ./provide/node2.yml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
  "@Sakura":
    type: http
    url: 'your url'
    path: ./provide/node3.yml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
```
