### ISSUE TITLE
订阅链接操作门槛高

### ISSUE THREAD

**Issue by 006hjy** [taamarin/box_for_magisk#45]
能否直接在Dashboard网页里面进行订阅链接的添加和更新？现在这个样子添加订阅链接必须要手动编辑文本添加，非常麻烦，操作门槛很高。要学习怎样添加订阅链接，怎样让它自动下载更新订阅。到现在都没整明白。
能否直接在Dashboard网页里面进行订阅链接的添加和更新？图形化的界面可以大大降低操作门槛

**Comment by 006hjy** [comment]
希望给Dashboard新增订阅管理的功能，支持通过网页导入订阅，给订阅设置cron自动更新。支持自动选择延迟最低的节点。

**Comment by aoxiangtianji** [comment]
dashboard是yacd项目，用API控制clash或者singbox内核。
但是没有任何一个内核支持通过API添加订阅。
至于选择如何自动延迟最低的节点，请去阅读clash的文档。

**Comment by 006hjy** [comment]
可以在rootforbox的APP上添加订阅嘛

**Comment by zhiim** [comment]
可以在clash meta的配置文件中的[proxy-providers](https://wiki.metacubex.one/config/proxy-providers/)添加订阅链接
```yaml
proxy-providers:
  provider1:
    type: http
    url: "http://test.com"
    path: ./proxy_providers/provider1.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      expected-status: 204
    override:
      skip-cert-verify: true
      udp: true
      down: "50 Mbps"
      up: "10 Mbps"
      dialer-proxy: proxy
      interface-name: tailscale0
      routing-mark: 233
      ip-version: ipv4-prefer
      additional-prefix: "provider1 prefix |"
      additional-suffix: "| provider1 suffix"
    filter: "(?i)港|hk|hongkong|hong kong"
    exclude-filter: "xxx"
    exclude-type: "ss|http"

  provider2:
    type: file
    path: ./proxy_providers/provider2.yaml
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
```
