### ISSUE TITLE
ipv6 回环问题

### ISSUE THREAD

**Issue by flyflas** [taamarin/box_for_magisk#83]
使用box for magisk。在开启ipv6时，出现回环。

发生回环的日志如下：

``` 
 time="2024-01-27T04:08:16.421281998Z" level=info msg="[TCP] 10.8.168.130:45642 --> cdn-mum.alibabachengdun.com:80 match GeoSite(cn) using DIRECT"
time="2024-01-27T04:08:16.787135956Z" level=info msg="[TCP] 10.8.168.130:49332 --> api.kingdata.ksyun.com:80 match GeoSite(cn) using DIRECT"
time="2024-01-27T04:08:16.978507466Z" level=info msg="[UDP] 10.8.168.130:44456(com.taobao.taobao, uid=10289) --> 27.222.18.252:443 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:16.982510695Z" level=info msg="[TCP] 10.8.168.130:38032 --> 59.82.9.145:80 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:17.097762362Z" level=info msg="[UDP] 10.8.168.130:39367(com.taobao.taobao, uid=10289) --> 111.206.225.225:443 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:17.138356164Z" level=info msg="[TCP] [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:40314(com.taobao.taobao, uid=10289) --> [2408:4001:f00::2a2]:443 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:17.153735747Z" level=info msg="[TCP] 10.8.168.130:46286 --> 27.222.18.251:80 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:17.376748456Z" level=info msg="[TCP] [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:40574(com.taobao.taobao, uid=10289) --> [2408:872f:900:9:3::3f7]:443 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:17.392426372Z" level=info msg="[TCP] 10.8.168.130:46070 --> guide-acs.m.taobao.com:443 match GeoSite(cn) using DIRECT"
time="2024-01-27T04:08:17.60409106Z" level=info msg="[TCP] [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:42246(com.tencent.mm, uid=10264) --> [2408:80f1:21:5001::19]:80 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:17.924612883Z" level=info msg="[TCP] 10.8.168.130:41732 --> cdn.ynuf.aliapp.org:80 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:18.120202101Z" level=info msg="[TCP] 10.8.168.130:40150(com.taobao.taobao, uid=10289) --> 123.125.216.235:80 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:18.332215382Z" level=info msg="[TCP] 10.8.168.130:49498 --> mpush-api.aliyun.com:443 match GeoSite(cn) using DIRECT"
time="2024-01-27T04:08:18.458856893Z" level=info msg="[TCP] 10.8.168.130:37926 --> mum.alibabachengdun.com:443 match GeoSite(cn) using DIRECT"
time="2024-01-27T04:08:19.178144965Z" level=info msg="[TCP] 10.8.168.130:40564(com.taobao.taobao, uid=10289) --> 61.48.83.231:443 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:19.188444288Z" level=info msg="[TCP] 10.8.168.130:43894(com.taobao.taobao, uid=10289) --> 61.48.83.231:80 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:19.485862778Z" level=info msg="[UDP] [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:42497(com.taobao.taobao, uid=10289) --> [2408:4001:f10::21f]:443 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:19.559882882Z" level=info msg="[UDP] [2408:4001:f10::21f]:443(clash) --> [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:42497 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:19.571622569Z" level=info msg="[UDP] [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:42007(clash) --> [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:42497 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:19.613739132Z" level=info msg="[UDP] [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:46502(clash) --> [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:42497 match GeoIP(CN) using DIRECT"
time="2024-01-27T04:08:19.629892257Z" level=info msg="[UDP] [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:46806(clash) --> [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:42497 match GeoIP(CN) using DIRECT"


```

在此之后，一直有这样的回环：
```
time="2024-01-27T04:08:19.629892257Z" level=info msg="[UDP] [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:46806(clash) --> [2408:8406:1981:2bf1:2017:68c9:9146:2d02]:42497 match GeoIP(CN) using DIRECT"
```

DNS设置如下

``` yaml
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  use-hosts: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  default-nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 127.0.0.1:53
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://8.8.8.8/dns-query#🔬 Dns Proxy
  - https://1.1.1.1/dns-query#🔬 Dns Proxy
  fallback:
  - https://8.8.8.8/dns-query#🔬 Dns Proxy
  - https://1.1.1.1/dns-query#🔬 Dns Proxy
  nameserver-policy:
    geosite:private:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    geosite:geolocation-!cn:
    - https://dns.cloudflare.com/dns-query#🔬 Dns Proxy
    - https://dns.google/dns-query#🔬 Dns Proxy
```

mihomo issue: [#926](https://github.com/MetaCubeX/mihomo/issues/926)

不知道是不是防火墙规则的问题。还请各位大佬指教。
